use shopped;
select * from unit;
set @dr = (select id from unit where abbrev = "dr");
set @ds = (select id from unit where abbrev = "ds");
set @pn = (select id from unit where abbrev = "pn");
set @tsp = (select id from unit where abbrev = "tsp");
set @tbsp = (select id from unit where abbrev = "tbsp");
set @C = (select id from unit where abbrev = "C");
set @l = (select id from unit where abbrev = "l");
set @ml = (select id from unit where abbrev = "ml");
set @g = (select id from unit where abbrev = "g");
set @kg = (select id from unit where abbrev = "kg");
set @cm = (select id from unit where abbrev = "cm");
set @in = (select id from unit where abbrev = "in");

insert into ingredient (name, unit_id, status)
values
	("vanilla",@dr,"ACTIVE"),
	("allspice",@g,"ACTIVE"),
	("almond",@g,"ACTIVE"),
	("all-purpose flour",@g,"ACTIVE"),
	("amaretti",@g,"ACTIVE"),
	("anchovy",@g,"ACTIVE"),
	("anise",@g,"ACTIVE"),
	("apple juice",@ml,"ACTIVE"),
	("artichoke",@g,"ACTIVE"),
	("artichoke heart",@g,"ACTIVE"),
	("artichoke",@g,"ACTIVE"),
	("asparagus",@g,"ACTIVE"),
	("asparagus spear",@g,"ACTIVE"),
	("aubergine",@g,"ACTIVE"),
	("avocado",@g,"ACTIVE"),
	("bacon",@kg,"ACTIVE"),
	("baguette",@g,"ACTIVE"),
	("baked beans",@g,"ACTIVE"),
	("balsamic vinegar",@ml,"ACTIVE"),
	("bamboo",@in,"ACTIVE"),
	("banana",@g,"ACTIVE"),
	("bap",@g,"ACTIVE"),
	("basil",@g,"ACTIVE"),
	("bay leaf",@g,"ACTIVE"),
	("bay leaves",@g,"ACTIVE"),
	("bean",@g,"ACTIVE"),
	("beef",@kg,"ACTIVE"),
	("beef mince",@kg,"ACTIVE"),
	("beef brisket",@kg,"ACTIVE"),
	("beef stock",@kg,"ACTIVE"),
	("bell pepper",@g,"ACTIVE"),
	("berry",@g,"ACTIVE"),
	("berries",@g,"ACTIVE"),
	("bicarbonate of soda",@g,"ACTIVE"),
	("biscuit",@g,"ACTIVE"),
	("biscuit",@g,"ACTIVE"),
	("black olive",@g,"ACTIVE"),
	("black pepper",@g,"ACTIVE"),
	("black-eyed peas",@g,"ACTIVE"),
	("blueberries",@g,"ACTIVE"),
	("blueberry",@g,"ACTIVE"),
	("bonnet chilli",@g,"ACTIVE"),
	("bouillon",@g,"ACTIVE"),
	("bourbon",@g,"ACTIVE"),
	("braising steak",@g,"ACTIVE"),
	("bran",@g,"ACTIVE"),
	("brandy",@g,"ACTIVE"),
	("bread",@g,"ACTIVE"),
	("breadcrumbs",@g,"ACTIVE"),
	("bbq sauce",@g,"ACTIVE"),
	("habanero sauce",@g,"ACTIVE"),
	("brie",@g,"ACTIVE"),
	("brine",@g,"ACTIVE"),
	("broccoli",@g,"ACTIVE"),
	("brown rice",@g,"ACTIVE"),
	("brown sauce",@g,"ACTIVE"),
	("brown sugar",@g,"ACTIVE"),
	("buckwheat",@g,"ACTIVE"),
	("buffalo",@g,"ACTIVE"),
	("bun",@g,"ACTIVE"),
	("butter",@g,"ACTIVE"),
	("buttermilk",@g,"ACTIVE"),
	("butternut",@g,"ACTIVE"),
	("butternut squash",@g,"ACTIVE"),
	("butterscotch",@g,"ACTIVE"),
	("cabbage",@g,"ACTIVE"),
	("cake",@g,"ACTIVE"),
	("candy",@g,"ACTIVE"),
	("candies",@g,"ACTIVE"),
	("cannellini",@g,"ACTIVE"),
	("canola oil",@ml,"ACTIVE"),
	("caper",@g,"ACTIVE"),
	("caramel",@g,"ACTIVE"),
	("caraway seed",@g,"ACTIVE"),
	("cardamom",@g,"ACTIVE"),
	("carrot",@g,"ACTIVE"),
	("carrot",@g,"ACTIVE"),
	("cashew",@g,"ACTIVE"),
	("caster sugar",@g,"ACTIVE"),
	("cayenne pepper",@g,"ACTIVE"),
	("celeriac",@g,"ACTIVE"),
	("celery",@g,"ACTIVE"),
	("cereal",@g,"ACTIVE"),
	("champagne",@g,"ACTIVE"),
	("chard",@g,"ACTIVE"),
	("cheddar cheese",@g,"ACTIVE"),
	("cheese",@g,"ACTIVE"),
	("cherries",@g,"ACTIVE"),
	("cherry",@g,"ACTIVE"),
	("cherry tomatoe",@g,"ACTIVE"),
	("chestnut",@g,"ACTIVE"),
	("chicken",@g,"ACTIVE"),
	("chicken breast",@g,"ACTIVE"),
	("chicken drumstick",@g,"ACTIVE"),
	("chicken stock",@g,"ACTIVE"),
	("chicken thigh",@g,"ACTIVE"),
	("chicken leg",@g,"ACTIVE"),
	("chicken",@g,"ACTIVE"),
	("chickpea",@g,"ACTIVE"),
	("chicory",@g,"ACTIVE"),
	("chile",@g,"ACTIVE"),
	("chilli",@g,"ACTIVE"),
	("chillies",@g,"ACTIVE"),
	("chipotle",@g,"ACTIVE"),
	("chip",@g,"ACTIVE"),
	("chive",@g,"ACTIVE"),
	("chive",@g,"ACTIVE"),
	("chocolate",@g,"ACTIVE"),
	("chop",@g,"ACTIVE"),
	("choy",@g,"ACTIVE"),
	("chutney",@g,"ACTIVE"),
	("ciabatta",@g,"ACTIVE"),
	("cider",@g,"ACTIVE"),
	("cinnamon",@g,"ACTIVE"),
	("clam",@g,"ACTIVE"),
	("clarified butter",@g,"ACTIVE"),
	("clove",@g,"ACTIVE"),
	("cocoa",@g,"ACTIVE"),
	("coconut",@g,"ACTIVE"),
	("orange essence",@ml,"ACTIVE"),
	("almond essence",@ml,"ACTIVE"),
	("coconut milk",@l,"ACTIVE"),
	("cod",@g,"ACTIVE"),
	("coffee",@l,"ACTIVE"),
	("coleslaw",@g,"ACTIVE"),
	("condensed milk",@g,"ACTIVE"),
	("coriander",@g,"ACTIVE"),
	("coriander leaves",@g,"ACTIVE"),
	("corn",@g,"ACTIVE"),
	("cornflour",@g,"ACTIVE"),
	("cornmeal",@g,"ACTIVE"),
	("courgette",@g,"ACTIVE"),
	("couscous",@g,"ACTIVE"),
	("cranberries",@g,"ACTIVE"),
	("cranberry",@g,"ACTIVE"),
	("cranberry juice",@ml,"ACTIVE"),
	("cream",@g,"ACTIVE"),
	("single cream",@g,"ACTIVE"),
	("double cream",@g,"ACTIVE"),
	("sour cream",@g,"ACTIVE"),
	("crﾏme fraiche",@g,"ACTIVE"),
	("crisp",@g,"ACTIVE"),
	("crust",@g,"ACTIVE"),
	("creme de cassis",@g,"ACTIVE"),
	("cucumber",@g,"ACTIVE"),
	("cumin",@g,"ACTIVE"),
	("custard",@g,"ACTIVE"),
	("dijon mustard",@g,"ACTIVE"),
	("dill",@g,"ACTIVE"),
	("duck",@kg,"ACTIVE"),
	("edamame bean",@g,"ACTIVE"),
	("egg",@g,"ACTIVE"),
	("espresso",@g,"ACTIVE"),
	("fennel",@g,"ACTIVE"),
	("feta",@g,"ACTIVE"),
	("fig",@g,"ACTIVE"),
	("fillet steak",@g,"ACTIVE"),
	("filo pastry",@g,"ACTIVE"),
	("fish",@g,"ACTIVE"),
	("flank",@g,"ACTIVE"),
	("flour",@g,"ACTIVE"),
	("focaccia",@g,"ACTIVE"),
	("foie gras",@g,"ACTIVE"),
	("fruit",@g,"ACTIVE"),
	("fudge",@g,"ACTIVE"),
	("garam masala",@g,"ACTIVE"),
	("garlic",@g,"ACTIVE"),
	("gelatine",@g,"ACTIVE"),
	("gin",@g,"ACTIVE"),
	("ginger",@g,"ACTIVE"),
	("glucose",@g,"ACTIVE"),
	("goat",@g,"ACTIVE"),
	("goat's cheese",@g,"ACTIVE"),
	("golden syrup",@g,"ACTIVE"),
	("gorgonzola",@g,"ACTIVE"),
	("gouda",@g,"ACTIVE"),
	("grape",@g,"ACTIVE"),
	("grapefruit",@g,"ACTIVE"),
	("grape",@g,"ACTIVE"),
	("grapeseed",@g,"ACTIVE"),
	("green olive",@g,"ACTIVE"),
	("green pepper",@g,"ACTIVE"),
	("green",@g,"ACTIVE"),
	("gruyere",@g,"ACTIVE"),
	("gruyere cheese",@g,"ACTIVE"),
	("haddock",@g,"ACTIVE"),
	("ham",@g,"ACTIVE"),
	("harissa",@g,"ACTIVE"),
	("herbs",@g,"ACTIVE"),
	("hoisin",@g,"ACTIVE"),
	("hoisin sauce",@g,"ACTIVE"),
	("honey",@g,"ACTIVE"),
	("honeydew melon",@g,"ACTIVE"),
	("horseradish",@g,"ACTIVE"),
	("iceberg lettuce",@g,"ACTIVE"),
	("icing sugar",@g,"ACTIVE"),
	("jalapeno pepper",@g,"ACTIVE"),
	("juice",@ml,"ACTIVE"),
	("julienne",@g,"ACTIVE"),
	("kalamata olives",@g,"ACTIVE"),
	("ketchup",@g,"ACTIVE"),
	("kidney bean",@g,"ACTIVE"),
	("lager",@g,"ACTIVE"),
	("lamb",@g,"ACTIVE"),
	("lard",@g,"ACTIVE"),
	("lardons",@g,"ACTIVE"),
	("lasagne",@g,"ACTIVE"),
	("lavender",@g,"ACTIVE"),
	("leek",@g,"ACTIVE"),
	("lemon",@g,"ACTIVE"),
	("lemongrass",@g,"ACTIVE"),
	("lentil",@g,"ACTIVE"),
	("lettuce",@g,"ACTIVE"),
	("lime",@g,"ACTIVE"),
	("limoncello",@g,"ACTIVE"),
	("lobster",@g,"ACTIVE"),
	("loin",@g,"ACTIVE"),
	("lychee",@g,"ACTIVE"),
	("macadamia nut",@g,"ACTIVE"),
	("malt",@g,"ACTIVE"),
	("mangetout",@g,"ACTIVE"),
	("mango",@g,"ACTIVE"),
	("mangoes",@g,"ACTIVE"),
	("maple syrup",@g,"ACTIVE"),
	("marinara",@g,"ACTIVE"),
	("marshmallow",@g,"ACTIVE"),
	("marzano",@g,"ACTIVE"),
	("mascarpone",@g,"ACTIVE"),
	("mayonnaise",@g,"ACTIVE"),
	("meat",@g,"ACTIVE"),
	("melon",@g,"ACTIVE"),
	("milk",@g,"ACTIVE"),
	("mince",@g,"ACTIVE"),
	("mint",@g,"ACTIVE"),
	("miso soup",@g,"ACTIVE"),
	("molasses",@g,"ACTIVE"),
	("monterey jack",@g,"ACTIVE"),
	("mozzarella",@g,"ACTIVE"),
	("mushroom",@g,"ACTIVE"),
	("mustard",@g,"ACTIVE"),
	("new potato",@g,"ACTIVE"),
	("noodle",@g,"ACTIVE"),
	("nutella",@g,"ACTIVE"),
	("nutmeg",@g,"ACTIVE"),
	("nut",@g,"ACTIVE"),
	("oat",@g,"ACTIVE"),
	("oil",@ml,"ACTIVE"),
	("okra",@g,"ACTIVE"),
	("olive oil",@ml,"ACTIVE"),
	("olive",@g,"ACTIVE"),
	("onion",@g,"ACTIVE"),
	("onion ring",@g,"ACTIVE"),
	("orange",@g,"ACTIVE"),
	("orange juice",@ml,"ACTIVE"),
	("oregano",@g,"ACTIVE"),
	("oyster",@g,"ACTIVE"),
	("pak choi",@g,"ACTIVE"),
	("pancetta",@g,"ACTIVE"),
	("panko",@g,"ACTIVE"),
	("papaya",@g,"ACTIVE"),
	("paprika",@g,"ACTIVE"),
	("parma ham",@g,"ACTIVE"),
	("parmesan",@g,"ACTIVE"),
	("parmigiano",@g,"ACTIVE"),
	("parmigiano-reggiano",@g,"ACTIVE"),
	("parsley",@g,"ACTIVE"),
	("parsnip",@g,"ACTIVE"),
	("passion fruit",@g,"ACTIVE"),
	("pasta",@g,"ACTIVE"),
	("Pasta shell",@g,"ACTIVE"),
	("pastry",@g,"ACTIVE"),
	("pea",@g,"ACTIVE"),
	("peach",@g,"ACTIVE"),
	("peaches",@g,"ACTIVE"),
	("peanut",@g,"ACTIVE"),
	("peanut",@g,"ACTIVE"),
	("pear",@g,"ACTIVE"),
	("pea",@g,"ACTIVE"),
	("pecan",@g,"ACTIVE"),
	("pecorino",@g,"ACTIVE"),
	("penne",@g,"ACTIVE"),
	("penne pasta",@g,"ACTIVE"),
	("pepper",@g,"ACTIVE"),
	("peppercorn",@g,"ACTIVE"),
	("peppers",@g,"ACTIVE"),
	("pesto",@g,"ACTIVE"),
	("pickle",@g,"ACTIVE"),
	("pickled gherkin",@g,"ACTIVE"),
	("pickled onion",@g,"ACTIVE"),
	("pickled red onion",@g,"ACTIVE"),
	("pie",@g,"ACTIVE"),
	("pimento pepper",@g,"ACTIVE"),
	("pine nut",@g,"ACTIVE"),
	("pineapple",@g,"ACTIVE"),
	("pistachio",@g,"ACTIVE"),
	("pita",@g,"ACTIVE"),
	("pitta",@g,"ACTIVE"),
	("pitted olive",@g,"ACTIVE"),
	("pizza",@g,"ACTIVE"),
	("plantain",@g,"ACTIVE"),
	("plum",@g,"ACTIVE"),
	("plum tomato",@g,"ACTIVE"),
	("plum tomatoes",@g,"ACTIVE"),
	("sun dried tomato",@g,"ACTIVE"),
	("poblano",@g,"ACTIVE"),
	("pod",@g,"ACTIVE"),
	("polenta",@g,"ACTIVE"),
	("pomegranate",@g,"ACTIVE"),
	("popcorn",@g,"ACTIVE"),
	("pork",@g,"ACTIVE"),
	("Pork chop",@g,"ACTIVE"),
	("porridge",@g,"ACTIVE"),
	("potato",@g,"ACTIVE"),
	("potatoes",@g,"ACTIVE"),
	("prawn",@g,"ACTIVE"),
	("prosciutto",@g,"ACTIVE"),
	("prosciutto ham",@g,"ACTIVE"),
	("provolone",@g,"ACTIVE"),
	("pumpkin",@g,"ACTIVE"),
	("quail",@g,"ACTIVE"),
	("radicchio",@g,"ACTIVE"),
	("radish",@g,"ACTIVE"),
	("radishes",@g,"ACTIVE"),
	("rapeseed oil",@ml,"ACTIVE"),
	("raspberries",@g,"ACTIVE"),
	("raspberry",@g,"ACTIVE"),
	("red pepper",@g,"ACTIVE"),
	("red onion",@g,"ACTIVE"),
	("relish",@g,"ACTIVE"),
	("rhubarb",@g,"ACTIVE"),
	("rib",@g,"ACTIVE"),
	("rice",@g,"ACTIVE"),
	("ricotta",@g,"ACTIVE"),
	("rocket",@g,"ACTIVE"),
	("roll",@g,"ACTIVE"),
	("rose",@g,"ACTIVE"),
	("rosemary",@g,"ACTIVE"),
	("russet",@g,"ACTIVE"),
	("saffron",@g,"ACTIVE"),
	("sage",@g,"ACTIVE"),
	("sake",@g,"ACTIVE"),
	("salad",@g,"ACTIVE"),
	("salami",@g,"ACTIVE"),
	("salmon",@g,"ACTIVE"),
	("salmon flake",@g,"ACTIVE"),
	("salsa",@g,"ACTIVE"),
	("salt",@g,"ACTIVE"),
	("sauce",@g,"ACTIVE"),
	("sausage",@g,"ACTIVE"),
	("savoy cabbage",@g,"ACTIVE"),
	("scallop",@g,"ACTIVE"),
	("schnapps",@g,"ACTIVE"),
	("self raising flour",@g,"ACTIVE"),
	("semolina",@g,"ACTIVE"),
	("serrano ham",@g,"ACTIVE"),
	("shallot",@g,"ACTIVE"),
	("shaohsing",@g,"ACTIVE"),
	("sherry",@g,"ACTIVE"),
	("shiitake",@g,"ACTIVE"),
	("shiitake mushroom",@g,"ACTIVE"),
	("shortcrust pastry",@g,"ACTIVE"),
	("sirloin",@g,"ACTIVE"),
	("sirloin steak",@g,"ACTIVE"),
	("slaw",@g,"ACTIVE"),
	("smoky bacon",@g,"ACTIVE"),
	("snapper",@g,"ACTIVE"),
	("sourdough",@g,"ACTIVE"),
	("soy sauce",@g,"ACTIVE"),
	("spaghetti",@g,"ACTIVE"),
	("spice",@g,"ACTIVE"),
	("spinach",@g,"ACTIVE"),
	("sponge",@g,"ACTIVE"),
	("spring onion",@g,"ACTIVE"),
	("sprout",@g,"ACTIVE"),
	("squash",@g,"ACTIVE"),
	("squid",@g,"ACTIVE"),
	("sriracha",@g,"ACTIVE"),
	("steak",@g,"ACTIVE"),
	("stock",@g,"ACTIVE"),
	("stout",@g,"ACTIVE"),
	("strawberries",@g,"ACTIVE"),
	("strawberry",@g,"ACTIVE"),
	("stuffing",@g,"ACTIVE"),
	("sugar",@g,"ACTIVE"),
	("sultana",@g,"ACTIVE"),
	("sunflower oil",@ml,"ACTIVE"),
	("sweet pepper",@g,"ACTIVE"),
	("sweetcorn",@g,"ACTIVE"),
	("sweets",@g,"ACTIVE"),
	("swordfish",@g,"ACTIVE"),
	("tangerine",@g,"ACTIVE"),
	("tapioca",@g,"ACTIVE"),
	("tarragon",@g,"ACTIVE"),
	("tartar",@g,"ACTIVE"),
	("tea",@g,"ACTIVE"),
	("tequila",@g,"ACTIVE"),
	("thyme",@g,"ACTIVE"),
	("toast",@g,"ACTIVE"),
	("toffee",@g,"ACTIVE"),
	("tofu",@g,"ACTIVE"),
	("tomatillos",@g,"ACTIVE"),
	("tomato",@g,"ACTIVE"),
	("tomato puree",@g,"ACTIVE"),
	("tomatoes",@g,"ACTIVE"),
	("tortilla",@g,"ACTIVE"),
	("treacle",@g,"ACTIVE"),
	("tuna steak",@g,"ACTIVE"),
	("tuna",@g,"ACTIVE"),
	("turkey",@g,"ACTIVE"),
	("turkey breast",@g,"ACTIVE"),
	("turkey thigh",@g,"ACTIVE"),
	("turmeric",@g,"ACTIVE"),
	("turnip",@g,"ACTIVE"),
	("vanilla",@g,"ACTIVE"),
	("vanilla essence",@dr,"ACTIVE"),
	("vanilla pod",@dr,"ACTIVE"),
	("veal",@g,"ACTIVE"),
	("vegetable oil",@ml,"ACTIVE"),
	("vermouth",@g,"ACTIVE"),
	("vinaigrette",@ml,"ACTIVE"),
	("vinegar",@ml,"ACTIVE"),
	("white wine vinegar",@ml,"ACTIVE"),
	("red wine vinegar",@ml,"ACTIVE"),
	("vodka",@l,"ACTIVE"),
	("waffle",@g,"ACTIVE"),
	("walnut",@g,"ACTIVE"),
	("watercress",@g,"ACTIVE"),
	("watermelon",@g,"ACTIVE"),
	("white rice",@g,"ACTIVE"),
	("wholegrain pasta",@g,"ACTIVE"),
	("wine",@g,"ACTIVE"),
	("worcestershire sauce",@g,"ACTIVE"),
	("yeast",@g,"ACTIVE"),
	("yellow pepper",@g,"ACTIVE"),
	("greek yoghurt",@ml,"ACTIVE"),
	("natural yoghurt",@ml,"ACTIVE"),
	("yoghurt",@ml,"ACTIVE"),
	("yogurt",@ml,"ACTIVE"),
	("red onion",@g,"ACTIVE");
